# Definition

SVD is the final and best factorization of a matrix. Because $A$ can be any matrix, and $A$ can be factorized to the product of orthogonal matrix, diagonal matrix and orthogonal matrix.

$$A = U\Sigma V^T$$

# 


In [2]:
import numpy as np

A = np.random.randint(10, size=(3, 4))

def get_sorted_eig(matrix):
    values, vectors = np.linalg.eig(matrix)
    #if values[values<0]
    idx = values.argsort()[::-1]
    values = values[idx]
    vectors = vectors.T[idx].T
    return values, vectors

def SVD(A):
    # sort to let columns of U and columns of V corresponds to each other
    SV, V = get_sorted_eig(A.T@A)
    SU, U = get_sorted_eig(A@A.T)
    
    # eliminate computation errors
    SU[SU<0]=0
    lenU = len(SU)
    lenV = len(SV)
    
    S = np.sqrt(SU)
    
    # determine the sign of column vectors of U
    for i in range(min(lenU,lenV)):
        if np.allclose(A@ V[:,i], S[i]*U[:,i]) is False:
            U[:, i] = -U[:, i]
            
    S = np.diag(S)
    # crop sigma matrix
    if lenV > lenU:
        S = np.hstack((S, np.zeros((lenU, lenV-lenU))))
    elif lenV < lenU:
        S = S[:,:lenV]
    return S, U, V

def main():
    S, U, V = SVD(A)

    print("\n Original matrix A is")
    print(A)
    print("\n Sigma matrix is")
    print(S)
    print("\n Orthogonal matrix U is")
    print(U)
    print("\n Orthogonal matrix V is")
    print(V)
    print("\n Restruction matrix A is")
    print(U@S@V.T)
    
if __name__=="__main__":
    main()


 Original matrix A is
[[1 8 1 8]
 [5 7 8 5]
 [0 1 0 1]]

 Sigma matrix is
[[16.06956699  0.          0.          0.        ]
 [ 0.          6.06352027  0.          0.        ]
 [ 0.          0.          0.05233084  0.        ]]

 Orthogonal matrix U is
[[ 0.65127673 -0.74613335  0.13828828]
 [ 0.75502211  0.65540701 -0.01957727]
 [ 0.07602786 -0.11716093 -0.99019851]]

 Orthogonal matrix V is
[[ 0.27545156  0.41739808  0.77204866 -0.39223227]
 [ 0.65785198 -0.24711365 -0.40001471 -0.58834841]
 [ 0.41640535  0.74166862 -0.3502686   0.39223227]
 [ 0.56388279 -0.46329402  0.3481968   0.58834841]]

 Restruction matrix A is
[[ 1.00000000e+00  8.00000000e+00  1.00000000e+00  8.00000000e+00]
 [ 5.00000000e+00  7.00000000e+00  8.00000000e+00  5.00000000e+00]
 [ 4.33542091e-14  1.00000000e+00 -4.34097203e-14  1.00000000e+00]]
